# simulation settings
sim.1st_order_uncertainty = 1st-order uncertainty
sim.batch_iterations = Batch Iterations
sim.cohort = Cohort
sim.cohort_deterministic = Cohort (Deterministic)
sim.cohort_size = Cohort size
sim.cycles_per_year = Cycles per year
sim.first_order = First-order
sim.iteration_as_seed = Use iteration as RNG seed
sim.max_cycles = Max cycles
sim.model_uncertainty = Model Uncertainty
sim.monte_carlo = Monte Carlo
sim.monte_carlo_simulation = Monte Carlo simulation
sim.monte_carlo_simulations = Monte Carlo simulations
sim.monte_carlo_stochastic = Monte Carlo (Stochastic)
sim.multi_thread = Multi-thread simulation
sim.num_iterations = # Iterations
sim.num_simulations = # simulations
sim.number_of_simulations = Number of simulations
sim.rng_seed = RNG Seed
sim.sample_parameter_sets = Sample parameter sets
sim.sample_parameters = Sample Parameters
sim.second_order = Second-order
sim.seed = Seed
sim.seed_param_rng= Seed Parameter RNG
sim.seed_rng = Seed RNG
sim.set_to_max = Set to max
sim.simulation = Simulation
sim.simulation_type = Simulation type
sim.threads = Threads
sim.use_param_sets = Use Parameter Sets


# results
result.compile_traces = Compile traces
result.cum = Cum
result.cum_dis = Cum_Dis
result.cum_dis_lb = Cum_Dis_LB
result.cum_dis_mean = Cum_Dis_Mean
result.cum_dis_ub = Cum_Dis_UB
result.cum_lb = Cum_LB
result.cum_mean = Cum_Mean
result.cum_rewards_t = Cum. Rewards(t)
result.cum_ub = Cum_UB
result.cycle_dis = Cycle_Dis
result.cycle_dis_lb = Cycle_Dis_LB
result.cycle_dis_mean = Cycle_Dis_Mean
result.cycle_dis_ub = Cycle_Dis_UB
result.cycle_lb = Cycle_LB
result.cycle_mean = Cycle_Mean
result.cycle_ub = Cycle_UB
result.dis = (Dis)
result.discounted = Discounted
result.display_ind_results = Display individual-level results
result.estimate = Estimate
result.ev = EV
result.ev_results = EV Results
result.group = Group
result.Ind = Ind
result.individual_level_results = Individual-level Results
result.IndResults = IndResults
result.num_sims = Num_Sims
result.outcome = Outcome
result.outcome_summaries = Outcome Summaries
result.outcomes = Outcomes
result.overall = Overall
result.prev_t = Prev(t)
result.report_subgroup_outcomes = Report subgroup-specific outcomes
result.results = Results
result.rewards_cum = Rewards (Cum.)
result.rewards_cycle = Rewards (Cycle)
result.rewards_t = Rewards(t)
result.show_trace = Show trace
result.state_prevalence = State Prevalence
result.subgroup = Subgroup
result.subgroup_results = Subgroup Results
result.subgroups = Subgroups
result.trace = Trace
result.TreeReport = TreeReport
result.value = Value
result.values = Values
result.variables_cycle = Variables (Cycle)
result.variables_t = Variables(t)


# CEA
cea.additional_dimension = Additional Dimension
cea.baseline_strategy = Baseline Strategy
cea.ce_plane = C/E Plane
cea.cea_results = CEA Results
cea.cea_threshold = Cost-Effectiveness Threshold
cea.ceac = CEAC
cea.ceac_full = Cost-Effectiveness Acceptability Curve
cea.ceaf = CEAF
cea.ceaf_full = Cost-Effectiveness Acceptability Frontier
cea.cost = Cost
cea.cost_effectiveness_analysis = Cost-Effectiveness Analysis (CEA)
cea.cost_saving = Cost Saving
cea.ecea_results = ECEA Results
cea.effect = Effect
cea.effect_objective = Effect Objective
cea.extended_cea = Extended Cost-Effectiveness Analysis (ECEA)
cea.icer = ICER
cea.indifferent = Indifferent
cea.plot_wtp = Plot WTP
cea.ratio_of_means = Ratio of Means
cea.strongly_dominated = Strongly Dominated
cea.weakly_dominated = Weakly Dominated
cea.wtp = Willingness-to-pay (WTP)
cea.wtp_abbr = WTP
cea.wtp_per = Willingness-to-pay ({0} per {1})


# BCA
bca.bca_results = BCA Results
bca.benefit = Benefit
bca.benefit_cost_analysis = Benefit-Cost Analysis (BCA)
bca.nmb = NMB


# general
gen.analysis = Analysis
gen.analysis_type = Analysis type
gen.decimals = Decimals
gen.dimension = Dimension
gen.discount_rate = Discount Rate (%)
gen.discount_rewards = Discount Rewards
gen.discount_start_cycle = Discount start cycle
gen.expected_value = Expected Value (EV)
gen.half_cycle_correction = Half-cycle correction
gen.index = Index
gen.maximize = Maximize
gen.minimize = Minimize
gen.objective = Objective
gen.psa = PSA
gen.run_type = Run Type
gen.setting = Setting
gen.source = Source
gen.state_prev_decimals = State Prevalence Decimals
gen.strategies = Strategies
gen.strategy = Strategy
gen.symbol = Symbol


# sensitivity
sens.baseline = Baseline
sens.best_strategy = Best Strategy
sens.distance = Distance
sens.high = High
sens.low = Low
sens.one_way_sens_analysis = One-way Sensitivity Analysis
sens.pOptimal = p(Optimal)
sens.prob_sens_analysis = Probabilistic Sensitivity Analysis
sens.psa_iterations = PSA Iterations
sens.stacked_one_way = Stacked One-way Sensitivity Analyses
sens.threshold = Threshold
sens.tolerance = Tolerance
sens.two_way_sens_analysis = Two-way Sensitivity Analysis


# calibration
calib.abc = Approximate Bayesian Calibration
calib.calib_score_expression = Calibration Score Expression
calib.calib_settings = Calibration Settings
calib.method = Method
calib.num_param_sets = # Parameter Sets
calib.parameter_value = Parameter Value
calib.parameter_values = Parameter Values
calib.posterior_cdf = Posterior CDF
calib.posterior_density = Posterior Density
calib.posterior_frequency = Posterior Frequency
calib.posterior_quantile = Posterior Quantile
calib.random = Random
calib.score_threshold = Score Threshold


# voi
voi.bins = Bins
voi.estimand = Estimand
voi.evpi = EVPI
voi.evpi_difference = EVPI (Difference)
voi.evpi_full = Expected Value of Perfect Information (EVPI)
voi.evpi_iterations = EVPI Iterations
voi.evpi_report = EVPI Report
voi.evppi = EVPPI
voi.evppi_bins = EVPPI Bins
voi.evppi_full = Expected Value of Partial Perfect Information (EVPPI)
voi.evppi_method = EVPPI Method
voi.evppi_report = EVPPI Report
voi.export_evppi_bin_results = Export EVPPI Bin Results
voi.import_psa_results = Import PSA Results
voi.num_bins = # Bins
voi.num_inner = # Inner
voi.num_outer = # Outer
voi.pbest = p(Best)
voi.perfect_information = Perfect Information
voi.run_new_psa = Run New PSA
voi.two_level_monte_carlo = Two-level Monte Carlo