# menu items
menu.about_amua = About Amua
menu.batch_runs = Batch Runs
menu.calibrate_model = Calibrate Model
menu.check_markov_chain = Check Markov Chain
menu.cluster_run = Cluster Run
menu.console = Console
menu.copy = Copy
menu.cut = Cut
menu.decision_tree = Decision Tree
menu.document = Document
menu.edit = Edit
menu.english = English (EN)
menu.error_log = Error Log
menu.exit = Exit
menu.export = Export
menu.find = Find
menu.find_replace = Find/Replace
menu.french = French (FR)
menu.help = Help
menu.help_contents = Help Contents
menu.import = Import
menu.language = Language
menu.markov_model = Markov Model
menu.model = Model
menu.new = New
menu.notes = Notes
menu.one_way = One-way
menu.open_model = Open Model
menu.open_recent = Open Recent
menu.param_sets = Parameter Sets
menu.partial_info_EVPPI = Partial Perfect Information (EVPPI)
menu.paste = Paste
menu.perfect_info_EVPI = Perfect Information (EVPI)
menu.plot_function = Plot Function
menu.plot_surface = Plot Surface
menu.prob_PSA = Probabilistic (PSA)
menu.properties = Properties
menu.redo = Redo
menu.redo_action = Redo {0}
menu.replace = Replace
menu.report_bug_request = Report Bug/Request
menu.run = Run
menu.run_markov_chain = Run Markov Chain
menu.run_model = Run Model
menu.save = Save
menu.save_as = Save As
menu.save_console = Save Console
menu.save_model = Save Model
menu.scenarios = Scenarios
menu.sens_analysis = Sensitivity Analysis
menu.spanish = Spanish (ES)
menu.stacked_one_way = Stacked One-way
menu.threshold_analysis = Threshold Analysis
menu.tools = Tools
menu.tornado_diagram = Tornado Diagram
menu.two_way = Two-way
menu.undo = Undo
menu.undo_action = Undo {0}
menu.value_information = Value of Information


# buttons
button.add = Add
button.add_constraint = Add Constraint
button.add_cost = Add Cost (One-time Event)
button.add_dimension = Add Dimension
button.add_parameter = Add Parameter
button.add_remove_cost = Add/Remove Cost (One-time Event)
button.add_remove_var_updates = Add/Remove Variable Updates
button.add_subgroup = Add Subgroup
button.add_table = Add Table
button.add_variable = Add Variable
button.align_left = Align Left
button.align_right = Align Right
button.browse = Browse
button.build_expression = Build Expression
button.cancel = Cancel
button.change_node_type = Change Node Type
button.change_to_chance = Change to Chance Node
button.change_to_terminal = Change to Terminal Node
button.change_to_transition = Change to State Transition
button.check_model = Check Model
button.clear = Clear
button.clear_all = Clear All
button.clear_selection = Clear Selection
button.close = Close
button.collapse_branch = Collapse Branch
button.collapse_expand_branch = Collapse/Expand Branch
button.delete = Delete
button.delete_constraint = Delete Constraint
button.delete_parameter = Delete Parameter
button.delete_table = Delete Table
button.delete_variable = Delete Variable
button.deselect_all = De-Select All
button.edit_constraint = Edit Constraint
button.edit_parameter = Edit Parameter
button.edit_subgroup = Edit Subgroup
button.edit_table = Edit Table
button.edit_variable = Edit Variable
button.evaluate = Evaluate
button.expand_branch = Expand branch
button.export_all = Export all
button.highlight_use = Highlight Use
button.import_csv = Import CSV
button.insert_value = Insert Value
button.move_down = Move Down
button.move_up = Move Up
button.no = No
button.ocd = OCD
button.ok = OK
button.open = Open
button.opt_cur_display = Optimize Current Display
button.plot = Plot
button.refresh = Refresh
button.remove_cost = Remove Cost (One-time Event)
button.remove_dimension = Remove Dimension
button.remove_subgroup = Remove Subgroup
button.screenshot = Screenshot
button.select = Select
button.select_all = Select All
button.update = Update
button.update_expression = Update Expression
button.vertical_spacing = Vertical Spacing
button.yes = Yes
button.zoom = Zoom
button.zoom_in = Zoom In
button.zoom_out = Zoom Out


# objects
object.constraint = Constraint
object.constraints = Constraints
object.elements = Elements
object.expected_value = Expected Value
object.expression = Expression
object.initial_value = Initial Value
object.model_objects = Model Objects
object.name = Name
object.no_updates = No updates
object.object_type = Object Type
object.object_updates = Object Updates
object.overwrite_current = Overwrite current objects
object.parameter = Parameter
object.parameter_set = Parameter Set
object.parameters = Parameters
object.scenario = Scenario
object.scenario_name = Scenario Name
object.scope = Scope
object.score = Score
object.scores = Scores
object.set = Set
object.sets = Sets
object.size = Size
object.table = Table
object.tables = Tables
object.type = Type
object.variable = Variable
object.variables = Variables


# titles
title.add_cost = Add Cost
title.add_remove = Remove Cost
title.add_var_updates = Add Variable Updates
title.amua_update = Amua Update
title.batch_runs = Batch Runs (1st-order uncertainty)
title.change_properties = Change Properties
title.clear_param_sets = Clear Parameter Sets
title.define_cluster_run = Define Cluster Run
title.define_constraint = Define Constraint
title.define_parameter = Define Parameter
title.define_scenario = Define Scenario
title.define_subgroup = Define Subgroup
title.define_table = Define Table
title.define_variable = Define Variable
title.definition = Definition
title.delete_node = Delete Node
title.delete_subtree = Delete Subtree
title.description = Description
title.document_model = Document Model
title.edit_cost = Edit Cost
title.edit_name = Edit Name
title.edit_notes = Edit Notes
title.edit_payoff = Edit Payoff
title.edit_probability = Edit Probability
title.edit_rewards = Edit Rewards
title.edit_scenarios = Edit Scenarios
title.edit_termination_condition = Edit Termination Condition
title.edit_transition = Edit Transition
title.edit_var_updates = Edit Variable Updates
title.example = Example
title.export_batch_results = Export Batch Results
title.export_ceac_results = Export CEAC Results
title.export_ceaf_results = Export CEAF Results
title.export_compiled_traces = Export Compiled Traces
title.export_data = Export Data
title.export_graph_data = Export Graph Data
title.export_iterations = Export iterations
title.export_model = Export Model
title.export_param_sets = Export Parameter Sets
title.export_psa_results = Export PSA Results
title.export_separate_traces = Export Separate Traces
title.export_subgroup_data = Export Subgroup Data
title.export_table = Export Table
title.export_trace = Export Trace
title.general = General
title.import_model_objects_from = Import Model Objects from {0}
title.import_objects = Import Objects
title.import_param_sets = Import Parameter Sets
title.import_table = Import Table
title.level = Level
title.model_calibration = Model Calibration
title.model_diagram = Model Diagram
title.model_inputs = Model Inputs
title.model_properties = Model Properties
title.paste_table = Paste Table
title.property = Property
title.remove_var_updates = Remove Variable Updates
title.save_cluster_run_inputs = Save Cluster Run Inputs
title.select_documentation_folder = Select Documentation Folder
title.select_export_folder = Select Export Folder
title.this_model_amua = This model was developed in Amua
title.trace_format = Trace Format
title.look_in = Look in
title.file_name = File name
title.files_of_type = Files of type
title.all_files = All Files
title.save_in = Save in
title.up_one_level = Up One Level
title.home = Home
title.create_new_folder = Create New Folder
title.list = List
title.details = Details


# metadata
meta.created = Created
meta.created_by = Created by
meta.metadata = Metadata
meta.model_name = Model Name
meta.model_type = Model Type
meta.modified = Modified
meta.modified_by = Modified by
meta.version_created = Version created
meta.version_modified = Version modified


# nodes
node.all = All
node.chain = Chain
node.chance = Chance Node
node.decision = Decision Node
node.markov_chain = Markov Chain
node.markov_state = Markov State
node.node = Node
node.payoff = Payoff
node.state_transition = State Transition
node.terminal = Terminal Node
node.transition = Transition


# tables
table.add_column = Add Column
table.add_row = Add Row
table.boundary_condition = Boundary Condition
table.clamped = Clamped
table.cols = Cols
table.column = Column
table.column_name = Column name
table.cubic_splines = Cubic Splines
table.distribution = Distribution
table.edit_column_name = Edit Column Name
table.exact = Exact
table.extrapolate = Extrapolate
table.index = Index
table.inline = In-line
table.interpolate = Interpolate
table.interpolation_method = Interpolation Method
table.left_only = Left only
table.linear = Linear
table.lookup = Lookup
table.lookup_method = Lookup Method
table.matrix = Matrix
table.natural = Natural
table.not_a_knot = Not-a-knot
table.periodic = Periodic
table.remove_column = Remove Column
table.remove_row = Remove Row
table.right_only = Right only
table.row = Row
table.rows = Rows
table.separate_files = Separate Files
table.table_format = Table format
table.table_type = Table Type
table.truncate = Truncate
table.user_defined_empirical_distribution = User-defined (empirical) distribution
table.user_defined_lookup_table = User-defined Lookup Table


# markov
markov.arg_column = Column index (integer <font face=\"Consolas\">\u22650</font>), or column name as a <font face=\"Consolas\">string</font>
markov.arg_cycle = Cycle index, integer <font face=\"Consolas\">\u22650</font>
markov.chain_name = Markov Chain Name
markov.cycle = Cycle
markov.cycle_rewards = Cycle Rewards
markov.init_prob = Initial Probability
markov.markov = Markov
markov.markov_trace = Markov Trace
markov.markov_trace_summary = Markov Trace Summary
markov.markov_traces = Markov Traces
markov.state = State
markov.state_name = Markov State Name
markov.t_desc = Returns the current cycle index, starting from <font face=\"Consolas\">t=0</font>
markov.termination = termination
markov.termination_condition = Termination Condition
markov.time_cycle_index = Time (cycle index)
markov.trace_desc = Returns the <font face=\"Consolas\">column</font> trace value for the specified <font face=\"Consolas\">cycle</font>


# GPL
gpl.copyright = Copyright
gpl.gnu = GNU General Public License
gpl.gpl_console = Amua is free software and is distributed in the hope that it will be useful, but comes with ABSOLUTELY NO WARRANTY
gpl.gpl_see_help = See Help -> About Amua for distribution details
gpl.gpl_text = Amua is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.\r\n\r\nAmua is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.\r\n\r\nYou should have received a copy of the GNU General Public License along with Amua.  If not, see <http://www.gnu.org/licenses/>.


# plots
plot.absolute = Absolute
plot.absolute_magnitude = Absolute Magnitude
plot.area_chart = Area Chart
plot.by_set = By Set
plot.change_series_colors = Change Series Colors
plot.choose_color_series = Choose color for series
plot.color = Color
plot.cumulative_distribution = Cumulative Distribution
plot.density = Density
plot.display_means = Display Means
plot.flip_axes = Flip Axes
plot.frequency = Frequency
plot.histogram = Histogram
plot.intervals = Intervals
plot.iteration = Iteration
plot.label_size = Label size
plot.marker_size = Marker size
plot.multi_plot = Multi-plot
plot.none = None
plot.order = Order
plot.parameter_labels = Parameter Labels
plot.plots = Plots
plot.quantile = Quantile
plot.quantiles = Quantiles
plot.relative = Relative
plot.relative_baseline = Relative to Baseline
plot.scatter = Scatter
plot.select_color = Select Color
plot.series = Series
plot.surface_chart = Surface Chart
plot.update_plot = Update Plot


# files
file.amua = Amua Model
file.cpp = C++ source files
file.csv = CSV
file.csv_full = Comma-separated values file
file.describe_rmarkdown = Creates an R Markdown file (.Rmd) that documents the model.  This can in turn be output to different formats (HTML, PDF, Word, etc).
file.filepath = Filepath
file.gif = GIF Graphics Interchange Format
file.java = Java source files
file.jpeg = JPEG File Interchange Format
file.png = PNG Portable Network Graphics Format
file.py = Python source files
file.py3_source = Python 3 source files (requires NumPy library)
file.r = R files
file.r_source = R source files
file.rmarkdown = R Markdown
file.text = Text file
file.xml = XML Spreadsheet


# system
system.amua_version = Amua version
system.avail_processors = Available Processors
system.heap_free = Heap - Free Memory
system.heap_max = Heap - Max Memory
system.heap_total = Heap - Total Memory
system.heap_used = Heap - Used Memory
system.java_class_format_version = Java class format version number
system.java_class_path = Java class path
system.java_install_dir = Java installation directory
system.jit_compiler = Name of JIT compiler to use
system.jre_spec_name = Java Runtime Environment specification name
system.jre_spec_vendor = Java Runtime Environment specification vendor
system.jre_spec_version = Java Runtime Environment specification version
system.jre_vendor = Java Runtime Environment vendor
system.jre_version = Java Runtime Environment version
system.jvm_imp_name = Java Virtual Machine implementation name
system.jvm_imp_vendor = Java Virtual Machine implementation vendor
system.jvm_imp_version = Java Virtual Machine implementation version
system.jvm_spec_name = Java Virtual Machine specification name
system.jvm_spec_vendor = Java Virtual Machine specification vendor
system.jvm_spec_version = Java Virtual Machine specification version
system.os_arch = Operating system architecture
system.os_name = Operating system name
system.os_version = Operating system version
system.screen_resolution = Screen Resolution
system.screen_size = Screen Size
system.system_properties = System properties
system.temp_filepath = Default temp file path
system.vendor_url = Java vendor URL