# general
gen.sample = Sample
gen.distribution_functions = Distribution Functions
gen.moments = Moments
gen.discrete = Discrete
gen.shape_gt0 = Shape (<font face=\"Consolas\">>0</font>)
gen.num_trials = Number of trials (Integer <font face=\"Consolas\">>0</font>)
gen.location = Location
gen.scale_gt0 = Scale (<font face=\"Consolas\">>0</font>)
gen.degrees_freedom = Degrees of freedom (Integer <font face=\"Consolas\">>0</font>)
gen.pos_real_num = Positive real number
gen.real_num_gt0 = Real number <font face=\"Consolas\">>0</font>
gen.max_value = Maximum value
gen.min_value = Minimum value
gen.continuous = Continuous
gen.multivariate = Multivariate


# descriptions
desc.sample = Returns a random variable (mean in base case) from the distribution
desc.pmf = Returns the value of the PMF at <font face=\"Consolas\">{0}</font>
desc.pdf = Returns the value of the PDF at <font face=\"Consolas\">{0}</font>
desc.cdf = Returns the value of the CDF at <font face=\"Consolas\">{0}</font>
desc.quantile = Returns the quantile (inverse CDF) of the distribution at <font face=\"Consolas\">{0}</font>
desc.mean = Returns the mean of the distribution
desc.var = Returns the variance of the distribution
desc.prob_success = Probability of success
desc.sample_rounded = Returns a random variable (rounded mean in base case) from the distribution
desc.sample_median = Returns a random variable (median in base case) from the distribution

# Bern
bern.name = Bernoulli Distribution
bern.desc = The probability distribution of a single Boolean-valued outcome
bern.support = Integer in <font face=\"Consolas\">{0,1}</font>

# Beta
beta.name = Beta Distribution
beta.desc = A continuous distribution bounded by <font face=\"Consolas\">0</font> and <font face=\"Consolas\">1</font>.  Often used to model probabilities
beta.support = Real number in <font face=\"Consolas\">[0,1]</font>

# Bin
bin.name = Binomial Distribution
bin.desc = Used to model the number of successes that occur in a fixed number of repeated trials
bin.support = Integer in <font face=\"Consolas\">{0,1,...,n}</font>

# Cat
cat.name = Categorical Distribution
cat.desc = A discrete probability distribution of a random variable that can take on one of <font face=\"Consolas\">n</font> possible values
cat.params = Row vector of size <font face=\"Consolas\">n</font> containing event probabilities (real numbers in <font face=\"Consolas\">[0,1]</font>) that sum to <font face=\"Consolas\">1.0</font>
cat.support = Integer in <font face=\"Consolas\">{0,1,...,n-1}</font>

# Cauchy
cauchy.name = Cauchy Distribution
cauchy.desc = A bell-shaped distribution with heavy tails. <i>Note</i>: Mean and variance are undefined

# ChiSq
chiSq.name = Chi-Squared Distribution
chiSq.desc = Distribution of the sum of squares of <font face=\"Consolas\">k</font> independent standard normal variables

# Dir
dir.name = Dirichlet Distribution
dir.desc = A multivariate generalization of the Beta distribution
dir.params = Row vector of concentration parameters (Real numbers <font face=\"Consolas\">>0</font>)
dir.sample = Returns a random vector (row vector of means in base case) from the Dirichlet distribution
dir.mean = Returns a row vector of means of the Dirichlet distribution
dir.var = Returns the covariance matrix of the Dirichlet distribution
dir.pdf = Returns the value of the Dirichlet PDF at <font face=\"Consolas\"><b>x</b></font> where <font face=\"Consolas\"><b>x</b></font> contains real numbers in <font face=\"Consolas\">(0,1)</font> that sum to <font face=\"Consolas\">1.0</font>

# DUnif
dunif.name = Discrete Uniform Distribution
dunif.desc = Used to model a discrete distribution where all values are equally likely
dunif.min = Minimum value, inclusive (integer)
dunif.max = Maximum value, inclusive (integer)
dunif.support = Integer in <font face=\"Consolas\">{a,a+1,...,b}</font>

# Expo
expo.name = Exponential Distribution
expo.desc = Used to model the time between events with a constant average rate
expo.param = Average rate of events (<font face=\"Consolas\">>0</font>)

# Gamma
gamma.name = Gamma Distribution
gamma.desc = A continuous distribution that yields positive real numbers

# Geom
geom.name = Geometric Distribution
geom.desc = Used to model the number of successes that occur before the first failure
geom.support = Integer in <font face=\"Consolas\">{0,1,...}</font>

# Gumbel
gumbel.name = Gumbel Distribution
gumbel.desc = Used to model the distribution of the extrema (max/min) of a number of samples of various distributions

# HalfCauchy
halfCauchy.name = Half-Cauchy Distribution
halfCauchy.desc = Positive Half-Cauchy. <i>Note</i>: Mean and variance are undefined

# HalfNorm
halfNorm.name = Half-Normal Distribution
halfNorm.desc = Positive Half-Normal
halfNorm.param = Standard deviation <font face=\"Consolas\">>0</font>

# HGeom
hgeom.name = Hypergeometric Distribution
hgeom.desc = Used to model the number of successes in a fixed number of draws without replacement
hgeom.w = Number of possible successes (Integer <font face=\"Consolas\">>0</font>)
hgeom.b = Number of other possible outcomes (Integer <font face=\"Consolas\">>0</font>)
hgeom.n = Number of draws (Integer <font face=\"Consolas\">>0</font>)
hgeom.support = Integer in <font face=\"Consolas\">{0,1,...,<i>min</i>(w,n)}</font>

# Laplace
laplace.name = Laplace Distribution
laplace.desc = A continuous distribution that can be thought of as two Exponential distributions put back-to-back

# Logistics
logistic.name = Logistic Distribution
logistic.desc = A continuous distribution that resembles the Normal distribution in shape but has heavier tails

# LogNorm
logNorm.name = Log-Normal Distribution
logNorm.desc = A continuous distribution of a random variable whose logarithm follows a Normal distribution

# Multi
multi.name = Multinomial Distribution
multi.desc = A generalization of the Binomial distribution to multiple categories
multi.p = Row vector containing event probabilities (Real numbers in <font face=\"Consolas\">[0,1]</font> that sum to <font face=\"Consolas\">1.0</font>)
multi.sample = Returns a random vector (row vector of means in base case) from the Multinomial distribution
multi.mean = Returns a row vector of means of the Multinomial distribution
multi.var = Returns the covariance matrix of the Multinomial distribution

# MvNorm
mvNorm.name = Multivariate Normal Distribution
mvNorm.desc = A multivariate normal distribution
mvNorm.mu = Mean (column vector)
mvNorm.sigma = Covariance matrix (symmetric positive definite)
mvNorm.sample = Returns a random vector (<font face=\"Consolas\"><b>\u03BC</b></font> in base case) from the Multivariate Normal distribution. Column vector of real numbers
mvNorm.pdf = Returns the value of the Multivariate Normal PDF at <font face=\"Consolas\"><b>X</b></font> (column vector)

# NBin
nbin.name = Negative Binomial Distribution
nbin.desc = Used to model the number of successes that occur among repeated trials before a specified number of failures happen
nbin.r = Number of failures until the trials are stopped (Integer <font face=\"Consolas\">\u22650</font>)

# Norm
norm.name = Normal Distribution
norm.desc = Canonical bell-shaped distribution

# Pareto
pareto.name = Pareto Distribution
pareto.desc = A power law probability distribution
pareto.scale = Scale (<font face=\"Consolas\">>0</font>) minimum possible value of <font face=\"Consolas\">x</font>
pareto.shape = Shape (<font face=\"Consolas\">>0</font>) Pareto index

# PERT
pert.name = PERT Distribution (Program Evaluation and Review Technique)
pert.desc = The PERT method converts a Triangular distribution to a Beta-shaped distribution. It is often used in risk analysis to model subjective estimates
pert.min = Minimum value, inclusive
pert.mode = Mode (most likely value)
pert.max = Maximum value, exclusive
pert.support = Real number in <font face=\"Consolas\">[a,c)</font>

# Pois
pois.name = Poisson Distribution
pois.desc = Used to model the number of events that occur in a fixed interval of time/space with a constant average rate
pois.lambda = Average number of events in the interval (<font face=\"Consolas\">>0</font>)

# StudentT
student.mean_undefined = Mean is undefined for <font face=\"Consolas\">\u03BD\u22641</font>
student.var_undefined = Variance is undefined for <font face=\"Consolas\">\u03BD\u22641</font>
student.name = Student's t-distribution
student.desc = A bell-shaped distribution centered at <font face=\"Consolas\">0</font>

# Tri
tri.name = Triangular Distribution
tri.desc = A simple distribution to model the minimum, most likely, and maximum values of a random variable

# TruncNorm
truncNorm.name = Truncated Normal Distribution
truncNorm.desc = A normal distribution bound by min/max values
truncNorm.support = Real number in <font face=\"Consolas\">[a,b]</font>

# Unif
unif.name = Uniform Distribution
unif.desc = Used to model a continuous distribution where all values are equally likely
unif.support = Real number in <font face=\"Consolas\">[a,b)</font>

# Weibull
weibull.name = Weibull Distribution
weibull.desc = Often used to model time-to-failure

# Zipf
zipf.name = Zipf Distribution
zipf.desc = Used to model discrete power law distributions
zipf.s = Exponent (Real number <font face=\"Consolas\">>0</font>)
zipf.n = Number of elements (Integer <font face=\"Consolas\">\u22651</font>)
zipf.support = Integer in <font face=\"Consolas\">{1,2,...,n}</font>