# summmaries
sum.95_lb = 95% LB
sum.95_ub = 95% UB
sum.95_ui = 95% UI
sum.expected_value = Expected Value
sum.expected_values = Expected Values
sum.lb = LB
sum.max = Max
sum.maximum = Maximum
sum.mean = Mean
sum.median = Median
sum.min = Min
sum.minimum = Minimum
sum.q1 = Q2
sum.q1_25 = Q1 (25%)
sum.q3 = Q3
sum.q3_75 = Q3 (75%)
sum.range = Range
sum.sd = SD
sum.ub = UB
sum.undefined = Undefined


# probabilities
prob.probability = Probability


# constants
const.constant = Constant
const.eulers_number = Euler's number
const.eulers_desc = The <font face=\"Consolas\">double</font> value that is closer than any other to <font face=\"Consolas\">e</font>, the base of the natural logarithm
const.inf = Infinity
const.inf_desc = A constant holding the positive infinity of type <font face=\"Consolas\">double</font>
const.pi_desc = The <font face=\"Consolas\">double</font> value that is closer than any other to <font face=\"Consolas\">\u03C0</font>, the ratio of the circumference of a circle to its diameter


# functions
fx.function = Function
fx.functions = Functions
fx.arguments = Arguments
fx.bounding = Bounding
fx.combinatorial = Combinatorial
fx.error = Error
fx.logarithmic = Logarithmic
fx.logical = Logical
fx.prob_rate = Probability/Rate
fx.roots = Roots
fx.summary = Summary
fx.trigonometric = Trigonometric
fx.abs_name = Absolute Value
fx.abs_desc = Returns the absolute value of <font face=\"Consolas\">x</font>
fx.acos_name = Arccosine
fx.acos_desc = Returns the arccosine of <font face=\"Consolas\">x</font>
fx.asin_name = Arcsine
fx.asin_desc = Returns the arcsine of <font face=\"Consolas\">x</font>
fx.atan_name = Arctangent
fx.atan_desc = Returns the arctangent of <font face=\"Consolas\">x</font>
fx.bound_name = Bounded Value
fx.bound_desc = Bounds <font face=\"Consolas\">x</font> to be in <font face=\"Consolas\">[a,b]</font>
fx.cbrt_name = Cube Root
fx.cbrt_desc = Returns the cube root of <font face=\"Consolas\">x</font>
fx.ceil_name = Ceiling
fx.ceil_desc = Returns the nearest integer above <font face=\"Consolas\">x</font>
fx.choose_name = Binomial Coefficient
fx.choose_desc = Returns the Binomial coefficient (<font face=\"Consolas\">n</font> choose <font face=\"Consolas\">k</font>)
fx.cos_name = Cosine
fx.cos_desc = Returns the cosine of <font face=\"Consolas\">x</font>
fx.cosh_name = Hyperbolic Cosine
fx.cosh_desc = Returns the hyperbolic cosine of <font face=\"Consolas\">x</font>
fx.erf_name = Error Function
fx.erf_desc = Returns the error function evaluated at <font face=\"Consolas\">x</font>
fx.exp_name = Exponential Function
fx.exp_desc = Returns Euler's number <font face=\"Consolas\">e</font> raised to the power of <font face=\"Consolas\">x</font>
fx.fact_name = Factorial
fx.fact_desc = Returns <font face=\"Consolas\">n!</font> (the factorial of <font face=\"Consolas\">n</font>)
fx.floor_name = Floor
fx.floor_desc = Returns the nearest integer below <font face=\"Consolas\">x</font>
fx.gamma_name = Gamma Function
fx.gamma_desc = Returns the gamma function evaluated at <font face=\"Consolas\">x</font>
fx.hypot_name = Hypotenuse
fx.hypot_desc = Returns <font face=\"Consolas\">sqrt(x<sup>2</sup>+y<sup>2</sup>)</font> without intermediate overflow or underflow
fx.if_name = If Function
fx.if_desc = Returns <font face=\"Consolas\">a</font> if the expression is <font face=\"Consolas\">true</font> and <font face=\"Consolas\">b</font> if it is <font face=\"Consolas\">false</font>
fx.invErf_name = Inverse Error Function
fx.invErf_desc = Returns the inverse error function evaluated at <font face=\"Consolas\">x</font>
fx.log_name = Natural Log
fx.log_desc = Returns the natural logarithm (base <font face=\"Consolas\">e</font> of <font face=\"Consolas\">x</font>)
fx.logb_name = Base-b Log
fx.logb_desc = Returns the base-<font face=\"Consolas\">b</font> logarithm of <font face=\"Consolas\">x</font>
fx.logGamma_name = Log-Gamma Function
fx.logGamma_desc = Returns the log-Gamma function evaluated at <font face=\"Consolas\">x</font>
fx.log10_name = Base-10 Log
fx.log10_desc = Returns the base-<font face=\"Consolas\">10</font> logarithm of <font face=\"Consolas\">x</font>
fx.logit_name = Logit Function
fx.logit_desc = Returns the log odds of probability <font face=\"Consolas\">p</font>: i.e., <font face=\"Consolas\">log(p/(1-p))</font>
fx.logistic_name = Logistic Function
fx.logistic_desc = Returns the standard logistic transformation: <font face=\"Consolas\">1/(1+exp(-x))</font>
fx.max_desc = Returns the maximum of <font face=\"Consolas\">a</font> and <font face=\"Consolas\">b</font>
fx.min_desc = Returns the minimum of <font face=\"Consolas\">a</font> and <font face=\"Consolas\">b</font>
fx.probRescale_name = Probability Rescale
fx.probRescale_desc = Rescales a probability <font face=\"Consolas\">p</font> from time interval <font face=\"Consolas\">t1</font> to a new time interval <font face=\"Consolas\">t2</font>
fx.probToRate_name = Probability to Rate
fx.probToRate_desc = Converts a probability <font face=\"Consolas\">p</font> to a rate for a fixed time interval
fx.probToRate_desc2 = Converts a probability <font face=\"Consolas\">p</font> per time interval <font face=\"Consolas\">t1</font> to a rate per time interval <font face=\"Consolas\">t2</font>
fx.probit_name = Probit Function
fx.probit_desc = Returns the inverse of the standard normal CDF for probability <font face=\"Consolas\">p</font>
fx.rateToProb_name = Rate to Probability
fx.rateToProb_desc = Converts a rate <font face=\"Consolas\">r</font> to a probability for a fixed time interval
fx.rateToProb_desc2 = Converts a rate <font face=\"Consolas\">r</font> per time interval <font face=\"Consolas\">t1</font> to a probability per time interval <font face=\"Consolas\">t2</font>
fx.round_name = Round
fx.round_desc = Rounds <font face=\"Consolas\">x</font> to the nearest integer
fx.round_desc2 = Rounds <font face=\"Consolas\">x</font> to <font face=\"Consolas\">n</font> decimal places
fx.sin_name = Sine
fx.sin_desc = Returns the sine of <font face=\"Consolas\">x</font>
fx.sinh_name = Hyperbolic Sine
fx.sinh_desc = Returns the hyperbolic sine of <font face=\"Consolas\">x</font>
fx.sqrt_name = Square Root
fx.sqrt_desc = Returns the square root of <font face=\"Consolas\">x</font>
fx.tan_name = Tangent
fx.tan_desc = Returns the tangent of <font face=\"Consolas\">x</font>
fx.tanh_name = Hyperbolic Tangent
fx.tanh_desc = Returns the hyperbolic tangent of <font face=\"Consolas\">x</font>
fx.signum_name = Signum Function
fx.signum_desc = Returns the sign of <font face=\"Consolas\">x</font>
fx.mean_desc = Returns the mean of <font face=\"Consolas\">x<sub>1</sub>,x<sub>2</sub>,...,x<sub>n</sub></font>
fx.product_name = Product
fx.product_desc = Returns the product of <font face=\"Consolas\">x<sub>1</sub>,x<sub>2</sub>,...,x<sub>n</sub></font>
fx.quantile_desc = Returns the quantile(s) <font face=\"Consolas\">q</font> of <font face=\"Consolas\">x<sub>1</sub>,x<sub>2</sub>,...,x<sub>n</sub></font>
fx.sd_name = Standard Deviation
fx.sd_desc = Returns the standard deviation of <font face=\"Consolas\">x<sub>1</sub>,x<sub>2</sub>,...,x<sub>n</sub></font>
fx.sum_name = Sum
fx.sum_desc = Returns the sum of <font face=\"Consolas\">x<sub>1</sub>,x<sub>2</sub>,...,x<sub>n</sub></font>
fx.var_name = Variance
fx.var_desc = Returns the variance of <font face=\"Consolas\">x<sub>1</sub>,x<sub>2</sub>,...,x<sub>n</sub></font>
fx.bool_expr_eval = Boolean expression to evaluate
fx.integer = Integer
fx.integer_gte0 = Integer <font face=\"Consolas\">\u22650</font>
fx.lb_incl_real = Lower bound (inclusive), real number
fx.num_digits_opt = Number of digits (Integer <font face=\"Consolas\">\u22650</font>) (optional)
fx.obj_return_false = Object returned if <font face=\"Consolas\">false</font>
fx.obj_return_true = Object returned if <font face=\"Consolas\">true</font>
fx.prob_mat_01 = Probability (or matrix) in <font face=\"Consolas\">[0,1]</font>
fx.prob_time_opt = Probability time interval <font face=\"Consolas\">>0</font> (optional)
fx.quant_eval = Quantile(s) to evaluate. Real number (or row vector of real numbers) in <font face=\"Consolas\">[0,1]</font>
fx.rate_mat_gte0 = Rate (or matrix) <font face=\"Consolas\">\u22650</font>
fx.rate_time_opt = Rate time interval <font face=\"Consolas\">>0</font> (optional)
fx.real_num = Real number
fx.real_num_mat = Real number (or matrix)
fx.real_num_mat_11 = Real number (or matrix) in <font face=\"Consolas\">[-1,1]</font>
fx.real_num_mat_gt0 = Real number (or matrix) <font face=\"Consolas\">>0</font>
fx.real_num_mat_gte0 = Real number (or matrix) <font face=\"Consolas\">\u22650</font>
fx.real_nums_mats = Real numbers (or matrices)
fx.time_new = New time interval <font face=\"Consolas\">>0</font>
fx.time_orig = Original time interval <font face=\"Consolas\">>0</font>
fx.ub_incl_real = Upper bound (inclusive), real number


# operators
op.operator = Operator
op.operators = Operators
op.logical_operator = Logical Operator
op.update_operator= Update Operator
op.addition = Addition
op.subtraction = Subtraction
op.multiplication = Multiplication
op.division = Division
op.exponentiation = Exponentiation
op.modulus = Modulus
op.equal = Equal
op.not_equal = Not Equal
op.less_than = Less Than
op.greater_than = Greater Than
op.lte = Less Than Or Equal
op.gte = Greater Than Or Equal
op.and = And
op.or = Or
op.xor = Exclusive Or
op.real_nums = Real Numbers
op.real_and_mat = Real Number and Matrix
op.add_real = Returns the sum of two real numbers
op.add_real_mat = Returns the sum of a real number <font face=\"Consolas\">a</font> and a matrix <font face=\"Consolas\"><b>X</b></font>
op.matrices = Matrices
op.add_mat = Returns the sum of two conformable matrices
op.subtract_real = Returns the difference of two real numbers
op.subtract_real_mat = Returns the difference of a real number <font face=\"Consolas\">a</font> and a matrix <font face=\"Consolas\"><b>X</b></font>
op.subtract_mat = Returns the difference of two conformable matrices
op.mult_real = Returns the product of two real numbers
op.mult_real_mat = Returns the product of a real number <font face=\"Consolas\">a</font> and a matrix <font face=\"Consolas\"><b>X</b></font>
op.mult_mat = Returns the product of two conformable matrices
op.divide_real = Returns the quotient of two real numbers
op.mat_and_real = Matrix and Real Number
op.divide_mat = Returns a matrix <font face=\"Consolas\"><b>X</b></font> divided by a real number <font face=\"Consolas\">a</font>
op.exp_real = Returns <font face=\"Consolas\">a</font> raised to the power of <font face=\"Consolas\">b</font>
op.mat_pos_int = Matrix and Positive Integer
op.exp_mat = Returns a matrix <font face=\"Consolas\"><b>X</b></font> multiplied by itself <font face=\"Consolas\">n</font> times
op.mod_real = Returns the remainder of <font face=\"Consolas\">a</font> divided by <font face=\"Consolas\">b</font>
op.mod_mat = Returns a matrix of remainders of <font face=\"Consolas\"><b>X</b></font> divided by <font face=\"Consolas\">a</font>
op.equal_desc = Returns <font face=\"Consolas\">true</font> if two values are equal, and <font face=\"Consolas\">false</font> otherwise
op.returns = returns
op.not_equal_desc = Returns <font face=\"Consolas\">true</font> if two values are not equal, and <font face=\"Consolas\">false</font> otherwise
op.lt_desc = Returns <font face=\"Consolas\">true</font> if <font face=\"Consolas\">a</font> is less than <font face=\"Consolas\">b</font>, and <font face=\"Consolas\">false</font> otherwise
op.gt_desc = Returns <font face=\"Consolas\">true</font> if <font face=\"Consolas\">a</font> is greather than <font face=\"Consolas\">b</font>, and <font face=\"Consolas\">false</font> otherwise
op.lte_desc = Returns <font face=\"Consolas\">true</font> if <font face=\"Consolas\">a</font> is less than or equal to <font face=\"Consolas\">b</font>, and <font face=\"Consolas\">false</font> otherwise
op.gte_desc = Returns <font face=\"Consolas\">true</font> if <font face=\"Consolas\">a</font> is greater than or equal to <font face=\"Consolas\">b</font>, and <font face=\"Consolas\">false</font> otherwise
op.and_desc = Returns <font face=\"Consolas\">true</font> if both expressions are true, and <font face=\"Consolas\">false</font> otherwise
op.or_desc = Returns <font face=\"Consolas\">true</font> if at least one expression is true, and <font face=\"Consolas\">false</font> otherwise
op.xor_desc = Returns <font face=\"Consolas\">true</font> if only one expression is true (i.e., not both), and <font face=\"Consolas\">false</font> otherwise


# update operators
up.assignment = Assignment
up.results_in = results in
up.assign_desc = Updates the value of <font face=\"Consolas\">a</font> to equal <font face=\"Consolas\">b</font>
up.increment = Increment by <font face=\"Consolas\">1</font>
up.increment_desc = Increments the value of <font face=\"Consolas\">a</font> by <font face=\"Consolas\">1</font>
up.results_in_same = results in the same update as
up.decrement = Decrement by <font face=\"Consolas\">1</font>
up.decrement_desc = Decrements the value of <font face=\"Consolas\">a</font> by <font face=\"Consolas\">1</font>
up.increment_gen = Increment
up.increment_gen_desc = Increments the value of <font face=\"Consolas\">a</font> by <font face=\"Consolas\">b</font>
up.decrement_gen = Decrement
up.decrement_gen_desc = Decrements the value of <font face=\"Consolas\">a</font> by <font face=\"Consolas\">b</font>
up.mult = Multiplication Assignment
up.mult_desc = Multiplies the value of <font face=\"Consolas\">a</font> by <font face=\"Consolas\">b</font>
up.div = Division Assignment
up.div_desc = Divides the value of <font face=\"Consolas\">a</font> by <font face=\"Consolas\">b</font>


# matrix functions
mat.matrix_function = Matrix Function
mat.chol_name = Cholesky Decomposition
mat.chol_desc = Returns the Cholesky Decomposition (lower triangle) of <font face=\"Consolas\"><b>X</b></font>
mat.det_name = Determinant
mat.det_desc = Returns the determinant of <font face=\"Consolas\"><b>X</b></font>
mat.diag_name = Matrix Diagonals
mat.diag_desc = Returns the diagonal elements of <font face=\"Consolas\"><b>X</b></font> as a row vector
mat.iden_name = Identity Matrix
mat.iden_desc = Returns an identity matrix of size <font face=\"Consolas\">n</font>
mat.interpolate_name = Linear Interpolation
mat.interpolate_desc = Returns a linear interpolation of <font face=\"Consolas\"><b>Y</b></font> at <font face=\"Consolas\">x</font>
mat.inv_name = Inverse Matrix
mat.inv_desc = Returns the inverse of <font face=\"Consolas\"><b>X</b></font> using LU decomposition
mat.ncol_name = Number of Columns
mat.ncol_desc = Returns the number of columns in <font face=\"Consolas\"><b>X</b></font>
mat.norm_name = Matrix Norm
mat.norm_desc = Returns the norm of the matrix
mat.norm_desc_default = Returns the Frobenius norm of <font face=\"Consolas\"><b>X</b></font> (default)
mat.norm_desc_L = Returns the (vector induced) L-<font face=\"Consolas\">n</font> norm of <font face=\"Consolas\"><b>X</b></font>
mat.norm_desc_inf = Returns the (vector induced) infinity norm of <font face=\"Consolas\"><b>X</b></font>
mat.nrow_name = Number of Rows
mat.nrow_desc = Returns the number of rows in <font face=\"Consolas\"><b>X</b></font>
mat.renorm_name = Renormalize
mat.renorm_desc = Returns a row vector with the elements of <font face=\"Consolas\"><b>X</b></font> linearly renormalized to sum to <font face=\"Consolas\">1.0</font>
mat.rep_name = Replicate
mat.rep_desc = Returns a row vector of size <font face=\"Consolas\">n</font> filled with <font face=\"Consolas\">x</font>
mat.seq_name = Sequence
mat.seq_desc = Returns a sequence of evenly spaced numbers in <font face=\"Consolas\">[a,b]</font>
mat.seq_desc_default = Returns a row vector containing a sequence of numbers from <font face=\"Consolas\">a</font> to <font face=\"Consolas\">b</font> with default step size (<font face=\"Consolas\">1.0</font>)
mat.seq_desc_step = Returns a row vector containing a sequence of numbers from <font face=\"Consolas\">a</font> to <font face=\"Consolas\">b</font> with step size <font face=\"Consolas\">\u2206</font>
mat.softmax_name = Softmax Function (Normalized Exponential)
mat.softmax_desc = Returns a row vector with the exponentiated elements of <font face=\"Consolas\"><b>X</b></font> renormalized to sum to <font face=\"Consolas\">1.0</font>
mat.stack_name = Stack Row Vectors
mat.stack_desc = Returns a matrix of stacked row vectors
mat.tp_name = Matrix Transpose
mat.tp_desc = Returns the transpose of <font face=\"Consolas\"><b>X</b></font>
mat.tr_name = Matrix Trace
mat.tr_desc = Returns the trace (i.e., sum of diagonal elements) of <font face=\"Consolas\"><b>X</b></font>
mat.iden_size = Size of identity matrix (Integer <font face=\"Consolas\">>0</font>)
mat.interpolate_row_x = Row vector of <font face=\"Consolas\">x</font> values (in increasing order)
mat.interpolate_row_y = Row vector of corresponding <font face=\"Consolas\">y</font> values
mat.interpolate_x = <font face=\"Consolas\">x</font>-value at which to calculate interpolated value of <font face=\"Consolas\">y</font>
mat.matrix_spd = Symmetric positive definite (SPD) matrix
mat.matrix_square = Square matrix
mat.matrix_square_nonsingular = Square, non-singular matrix
mat.norm_n = L-<font face=\"Consolas\">n</font> norm (Integer) (optional)
mat.rep_n = Vector size (Integer <font face=\"Consolas\">>0</font>)
mat.rep_x = Real number to replicate
mat.row_vector_real = Row vector of real numbers
mat.row_vector_real_gt0 = Row vector of real numbers <font face=\"Consolas\">>0</font>
mat.row_vectors = Row vectors
mat.seq_a = Start of sequence (inclusive), real number
mat.seq_b = End of sequence (inclusive if step size allows), real number
mat.seq_step = Step size, real number <font face=\"Consolas\">>0</font> (optional)